# Generated by Django 3.2.6 on 2022-04-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_room_name_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.AddField(
            model_name='building',
            name='all_rooms',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
