# Generated by Django 3.2.6 on 2022-04-30 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20220430_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='name',
        ),
    ]
