# Generated by Django 3.2.6 on 2022-05-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_bookhostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookhostel',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
