# Generated by Django 3.2.6 on 2022-05-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_bookhostel_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='all_beds',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
